# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=255)),
                ('interface_description', models.TextField()),
                ('dhcp', models.BooleanField()),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('gateway_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('dns_servers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
