# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='routes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
