# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20160421_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='connection',
            field=models.CharField(default='Ethernet', max_length=255),
        ),
    ]
